"""Onboarding complete

Revision ID: 1468f9b6445d
Revises: d088158d3e60
Create Date: 2026-03-14 00:34:16.057041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1468f9b6445d'
down_revision: Union[str, None] = 'd088158d3e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'onboarding_complete')
    # ### end Alembic commands ###
