"""add interview session flow fields

Revision ID: 22c7a7a7c670
Revises: 6ddd77c54488
Create Date: 2026-02-14 17:32:56.279910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c7a7a7c670'
down_revision: Union[str, None] = '6ddd77c54488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('language', sa.Text(), nullable=False))
    op.add_column('interview_sessions', sa.Column('phase', sa.Text(), nullable=False))
    op.add_column('interview_sessions', sa.Column('current_index', sa.Integer(), nullable=False))
    op.add_column('interview_sessions', sa.Column('followup_count', sa.Integer(), nullable=False))
    op.add_column('interview_sessions', sa.Column('intro_score', sa.Integer(), nullable=True))
    op.add_column('interview_sessions', sa.Column('intro_feedback', sa.Text(), nullable=True))
    op.add_column('interview_sessions', sa.Column('intro_evaluation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'intro_evaluation_json')
    op.drop_column('interview_sessions', 'intro_feedback')
    op.drop_column('interview_sessions', 'intro_score')
    op.drop_column('interview_sessions', 'followup_count')
    op.drop_column('interview_sessions', 'current_index')
    op.drop_column('interview_sessions', 'phase')
    op.drop_column('interview_sessions', 'language')
    # ### end Alembic commands ###
