"""add rapid option

Revision ID: 74c1fb1fe0b0
Revises: 33f9d256703e
Create Date: 2026-04-18 13:09:53.425926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c1fb1fe0b0'
down_revision: Union[str, None] = '33f9d256703e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'interview_sessions',
        sa.Column('is_rapid', sa.Boolean(), nullable=False, server_default=sa.false())
    )    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'is_rapid')
    # ### end Alembic commands ###
