"""user_skill free-text custom_name support

Revision ID: 75d916acac19
Revises: 3dcbefa5f2bc
Create Date: 2026-05-12 05:25:16.519482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d916acac19'
down_revision: Union[str, None] = '3dcbefa5f2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('custom_name', sa.String(length=120), nullable=True))
    op.alter_column('user_skills', 'skill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('uq_user_custom_skill', 'user_skills', ['user_id', sa.text('lower(custom_name)')], unique=True, postgresql_where=sa.text('skill_id IS NULL AND custom_name IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_custom_skill', table_name='user_skills', postgresql_where=sa.text('skill_id IS NULL AND custom_name IS NOT NULL'))
    op.alter_column('user_skills', 'skill_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_skills', 'custom_name')
    # ### end Alembic commands ###
