"""Achivments tables

Revision ID: 8262fd031508
Revises: bc3b3f51bb17
Create Date: 2026-05-17 19:29:59.018755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8262fd031508'
down_revision: Union[str, None] = 'bc3b3f51bb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title_en', sa.String(length=120), nullable=False),
    sa.Column('title_ar', sa.String(length=120), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('tier', sa.String(length=20), server_default='bronze', nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('seen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index('ix_user_achievements_user_seen', 'user_achievements', ['user_id', 'seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_achievements_user_seen', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
