"""add question_text and make question_id nullable

Revision ID: 82cde10d62c3
Revises: 8598cc4f8e1f
Create Date: 2026-04-15 13:34:03.870957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cde10d62c3'
down_revision: Union[str, None] = '8598cc4f8e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('question_text', sa.Text(), nullable=True))
    op.alter_column('session_questions', 'question_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_questions', 'question_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('session_questions', 'question_text')
    # ### end Alembic commands ###
