"""User profiles with roles and skills

Revision ID: 838e8944edb8
Revises: d5746ca1adb3
Create Date: 2026-03-12 04:22:28.512651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '838e8944edb8'
down_revision: Union[str, None] = 'd5746ca1adb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'skill_id', name='uq_role_skill')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.add_column('profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('major', sa.String(length=120), nullable=True))
    op.add_column('profiles', sa.Column('university', sa.String(length=150), nullable=True))
    op.add_column('profiles', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('current_status', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('experiences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('roles', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'parent_id')
    op.drop_column('profiles', 'experiences')
    op.drop_column('profiles', 'projects')
    op.drop_column('profiles', 'languages')
    op.drop_column('profiles', 'certifications')
    op.drop_column('profiles', 'github_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'current_status')
    op.drop_column('profiles', 'graduation_year')
    op.drop_column('profiles', 'university')
    op.drop_column('profiles', 'major')
    op.drop_column('profiles', 'bio')
    op.drop_table('user_skills')
    op.drop_table('user_roles')
    op.drop_table('role_skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
