"""drift check

Revision ID: 8598cc4f8e1f
Revises: ba26c8655a95
Create Date: 2026-04-15 13:12:59.217472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8598cc4f8e1f'
down_revision: Union[str, None] = 'ba26c8655a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'last_name',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
