"""add current_sq_id to interview_sessions

Revision ID: 8ca641f80204
Revises: 22c7a7a7c670
Create Date: 2026-02-14 17:51:06.887618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca641f80204'
down_revision: Union[str, None] = '22c7a7a7c670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('current_sq_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'current_sq_id')
    # ### end Alembic commands ###
