"""update questions table

Revision ID: ba26c8655a95
Revises: fded6e684140
Create Date: 2026-04-01 17:40:59.960187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba26c8655a95'
down_revision: Union[str, None] = 'fded6e684140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('submitted_by', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('status', sa.String(20), server_default='approved', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'submitted_by')
    # ### end Alembic commands ###
