"""question source

Revision ID: bc3b3f51bb17
Revises: 75d916acac19
Create Date: 2026-05-14 19:28:02.991848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3b3f51bb17'
down_revision: Union[str, None] = '75d916acac19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('source', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Backfill existing rows with the legacy heuristic
    op.execute("""
        UPDATE session_questions
        SET source = CASE
            WHEN question_text IS NOT NULL THEN 'cv_generated'
            WHEN question_id   IS NOT NULL THEN 'bank'
            ELSE 'unknown'
        END
        WHERE source IS NULL;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_questions', 'source')
    # ### end Alembic commands ###