"""v2 interview rework

Revision ID: c5a3710c04fb
Revises: 689c884c3589
Create Date: 2026-05-10 09:20:46.398912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a3710c04fb'
down_revision: Union[str, None] = '689c884c3589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_relevance_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', 'user_id', name='uq_relevance_session_q_user')
    )
    op.create_table('question_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_question_votes_q_u')
    )
    op.add_column('interview_sessions', sa.Column('practice_mode', sa.Text(), server_default='free', nullable=False))
    op.add_column('interview_sessions', sa.Column('finished_early', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('interview_sessions', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('questions', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('upvotes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('questions', sa.Column('downvotes', sa.Integer(), server_default='0', nullable=False))
    op.drop_index('ix_roadmap_stages_roadmap_id', table_name='roadmap_stages')
    op.drop_index('ix_roadmap_tasks_stage_id', table_name='roadmap_tasks')
    op.drop_index('ix_user_roadmaps_user_id', table_name='user_roadmaps')
    # ### end Alembic commands ###
    op.execute("""
            CREATE OR REPLACE FUNCTION fn_recompute_question_status()
            RETURNS TRIGGER AS $$
            DECLARE
                q_status TEXT; q_up INTEGER; q_down INTEGER;
                total INTEGER; ratio NUMERIC;
            BEGIN
                SELECT status, upvotes, downvotes
                    INTO q_status, q_up, q_down
                    FROM questions WHERE id = NEW.question_id;

                IF q_status IS DISTINCT FROM 'pending' THEN RETURN NEW; END IF;

                total := q_up + q_down;
                IF total < 5 THEN RETURN NEW; END IF;

                ratio := q_up::NUMERIC / total::NUMERIC;

                IF ratio >= 0.7 THEN
                    UPDATE questions SET status = 'approved' WHERE id = NEW.question_id;
                ELSIF ratio <= 0.3 THEN
                    UPDATE questions
                        SET status = 'rejected',
                            rejection_reason = COALESCE(rejection_reason, 'Rejected by community vote')
                        WHERE id = NEW.question_id;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)

    op.execute("""
            DROP TRIGGER IF EXISTS trg_recompute_question_status ON questions;
            CREATE TRIGGER trg_recompute_question_status
                AFTER UPDATE OF upvotes, downvotes ON questions
                FOR EACH ROW EXECUTE FUNCTION fn_recompute_question_status();
        """)


def downgrade() -> None:
    # ✅ Drop trigger + function FIRST before touching the tables they reference
    op.execute("DROP TRIGGER IF EXISTS trg_recompute_question_status ON questions;")
    op.execute("DROP FUNCTION IF EXISTS fn_recompute_question_status();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_roadmaps_user_id', 'user_roadmaps', ['user_id'], unique=False)
    op.create_index('ix_roadmap_tasks_stage_id', 'roadmap_tasks', ['stage_id'], unique=False)
    op.create_index('ix_roadmap_stages_roadmap_id', 'roadmap_stages', ['roadmap_id'], unique=False)
    op.drop_column('questions', 'downvotes')
    op.drop_column('questions', 'upvotes')
    op.drop_column('questions', 'quality_score')
    op.drop_column('interview_sessions', 'finished_at')
    op.drop_column('interview_sessions', 'finished_early')
    op.drop_column('interview_sessions', 'practice_mode')
    op.drop_table('question_votes')
    op.drop_table('question_relevance_feedback')
    # ### end Alembic commands ###

