"""add skill focus and include tangible outcome to roadmap

Revision ID: e250e1faf2d4
Revises: 33a99951e752
Create Date: 2026-05-11 19:56:11.926509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e250e1faf2d4'
down_revision: Union[str, None] = '33a99951e752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_id_fkey', 'profiles', type_='foreignkey')
    op.add_column('user_roadmaps', sa.Column('skill_focus', sa.String(length=500), nullable=True))
    op.add_column('user_roadmaps', sa.Column('include_tangible_outcome', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roadmaps', 'include_tangible_outcome')
    op.drop_column('user_roadmaps', 'skill_focus')
    op.create_foreign_key('profiles_id_fkey', 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###
