"""add new columns for interview

Revision ID: fded6e684140
Revises: 1468f9b6445d
Create Date: 2026-04-01 17:09:42.442034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fded6e684140'
down_revision: Union[str, None] = '1468f9b6445d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'interview_sessions',
        sa.Column('question_source', sa.Text(), server_default='bank', nullable=False)
    )
    op.add_column(
        'interview_sessions',
        sa.Column('company', sa.Text(), nullable=True)
    )
    op.add_column(
        'interview_sessions',
        sa.Column('tech_ratio', sa.Integer(), server_default='50', nullable=False)
    )
    op.add_column(
        'interview_sessions',
        sa.Column('use_cv', sa.Boolean(), server_default=sa.text('false'), nullable=False)
    )

    op.add_column(
        'questions',
        sa.Column('question_type', sa.String(length=30), server_default='technical', nullable=False)
    )
    op.add_column(
        'questions',
        sa.Column('company', sa.String(length=150), nullable=True)
    )
    op.add_column(
        'questions',
        sa.Column('language', sa.String(length=10), server_default='en', nullable=False)
    )
    op.add_column(
        'questions',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True)
    )

    op.add_column(
        'session_questions',
        sa.Column('question_type', sa.Text(), nullable=True)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_questions', 'question_type')
    op.drop_column('questions', 'created_at')
    op.drop_column('questions', 'language')
    op.drop_column('questions', 'company')
    op.drop_column('questions', 'question_type')
    op.drop_column('interview_sessions', 'use_cv')
    op.drop_column('interview_sessions', 'tech_ratio')
    op.drop_column('interview_sessions', 'company')
    op.drop_column('interview_sessions', 'question_source')
    # ### end Alembic commands ###
